unpackaged/main/default/objects/Custom_Pricing__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <defaultValue>0.0</defaultValue>
    <inlineHelpText>The base price used in calculations. It&#39;s usage will depend on the selected Type. Allows up to 4 decimal places</inlineHelpText>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Custom_Pricing__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Custom Pricings</relationshipLabel>
    <relationshipName>Custom_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Custom_Pricing__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Pricings</relationshipLabel>
    <relationshipName>Custom_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Custom_Pricing__c/fields/Round_Sync_Price__c.field-meta.xml
<CustomField>
    <fullName>Round_Sync_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked and Sync Currencies is selected the pricing for non USD records will be rounded based on system settings. These can be adjusted under the Price Rounding Custom Metadata Type.</inlineHelpText>
    <label>Round Sync Price</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Custom_Pricing__c/fields/Sync_Currencies__c.field-meta.xml
<CustomField>
    <fullName>Sync_Currencies__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this box is checked any time this reecord is created or updated it will synchronize changes across all supported currencies. This will create/update records in all other supported currencies automatically</inlineHelpText>
    <label>Sync Currencies</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Custom_Pricing__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>The type of custom pricing this record corresponds to</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Custom_Pricing_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CustomPricingCurrencyHandlerTest.cls
@IsTest
public with sharing class CustomPricingCurrencyHandlerTest {
    @TestSetup
    static void setupData() {
        Product2 testProd = new Product2(
            Name = 'Test Product Custom Pricing',
            ProductCode = 'TST-PRD-CSTM-PRICE'
        );

        insert testProd;

        Id standardPricebookId = Test.getStandardPricebookId();

        insert new List<PricebookEntry>{
            new PricebookEntry(
                Pricebook2Id = standardPricebookId,
                Product2Id = testProd.Id,
                UnitPrice = 1500,
                CurrencyIsoCode = 'USD',
                IsActive = true
            ),
            new PricebookEntry(
                Pricebook2Id = standardPricebookId,
                Product2Id = testProd.Id,
                UnitPrice = 1500,
                CurrencyIsoCode = 'GBP',
                IsActive = true
            )
        };
    }

    @IsTest
    public static void testInsertCustomPricingWithRoundAndSync() {
        Id productId = [
            SELECT Id
            FROM Product2
            WHERE Name = 'Test Product Custom Pricing'
        ]
        .Id;

        Id standardPricebookId = Test.getStandardPricebookId();

        Test.startTest();

        insert new Custom_Pricing__c(
            Type__c = 'QCP - Increment Pricing',
            Product__c = productId,
            Price_Book__c = standardPricebookId,
            Base_Price__c = 15000,
            Minimum_Quantity__c = 1,
            Maximum_Quantity__c = 100000,
            CurrencyIsoCode = 'USD',
            Sync_Currencies__c = true,
            Round_Sync_Price__c = true
        );

        Test.stopTest();

        List<Custom_Pricing__c> customPricingResults = [
            SELECT Id, Base_Price__c
            FROM Custom_Pricing__c
            WHERE
                Product__c = :productId
                AND Price_Book__c = :standardPricebookId
                AND CurrencyIsoCode != 'USD'
        ];

        System.assert(
            customPricingResults.size() > 0,
            'Custom Pricing records were not created for other currencies when expected'
        );
    }

    @IsTest
    public static void testUpdateCustomPricingWithSyncOnly() {
        Id productId = [
            SELECT Id
            FROM Product2
            WHERE Name = 'Test Product Custom Pricing'
        ]
        .Id;

        Id standardPricebookId = Test.getStandardPricebookId();

        Custom_Pricing__c mainCustomPricing = new Custom_Pricing__c(
            Type__c = 'QCP - Increment Pricing',
            Product__c = productId,
            Price_Book__c = standardPricebookId,
            Base_Price__c = 15000,
            Minimum_Quantity__c = 1,
            Maximum_Quantity__c = 100000,
            CurrencyIsoCode = 'USD',
            Sync_Currencies__c = true
        );

        insert mainCustomPricing;

        Test.startTest();

        mainCustomPricing.Base_Price__c = 18000;

        update mainCustomPricing;

        Test.stopTest();

        List<Custom_Pricing__c> customPricingResults = [
            SELECT Id, Base_Price__c
            FROM Custom_Pricing__c
            WHERE
                Product__c = :productId
                AND Price_Book__c = :standardPricebookId
                AND CurrencyIsoCode != 'USD'
        ];

        System.assert(
            customPricingResults.size() > 0,
            'Custom Pricing records were not created for other currencies when expected'
        );
    }
}