unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Named_Account_Tier__c</fullName>
    <label>Named Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_6QA_End_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_End_Date__c</fullName>
    <label>6sense Account 6QA End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_6QA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_Start_Date__c</fullName>
    <label>6sense Account 6QA Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_Reach_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Reach_Score__c</fullName>
    <label>6sense Account Reach Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Awareness__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Awareness__c</fullName>
    <label>6sense Stage – Awareness</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Consideration__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Consideration__c</fullName>
    <label>6sense Stage – Consideration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Decision__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Decision__c</fullName>
    <label>6sense Stage – Decision</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Purchase__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Purchase__c</fullName>
    <label>6sense Stage – Purchase</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Account_Stage_at_Creation__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage_at_Creation__c</fullName>
    <label>Account Stage at Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Named_Account_Tier__c</fullName>
    <label>Named Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_6QA_End_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_End_Date__c</fullName>
    <label>6sense Account 6QA End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_6QA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_Start_Date__c</fullName>
    <label>6sense Account 6QA Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Buying_Stage__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Buying_Stage__c</fullName>
    <label>6sense Account Buying Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Intent_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Intent_Score__c</fullName>
    <label>6sense Account Intent Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Profile_Fit__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Profile_Fit__c</fullName>
    <label>6sense Account Profile Fit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Reach_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Reach_Score__c</fullName>
    <label>6sense Account Reach Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6Sense_Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>X6Sense_Segment_Name__c</fullName>
    <label>6Sense Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Awareness__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Awareness__c</fullName>
    <label>6sense Stage – Awareness</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Consideration__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Consideration__c</fullName>
    <label>6sense Stage – Consideration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Decision__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Decision__c</fullName>
    <label>6sense Stage – Decision</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Purchase__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Purchase__c</fullName>
    <label>6sense Stage – Purchase</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/classes/StageZeroOppInitializerTest.cls
@isTest
public with sharing class StageZeroOppInitializerTest {
    @TestSetup
    static void makeData() {
        insert new Account(
            Name = 'StageZeroOppInitializerTest',
            Account_Stage__c = 'Prospect',
            RecordTypeId = RecordTypeUtility.getId(
                Account.getSObjectType(),
                'Customer'
            ),
            X6sense_Account_6QA_End_Date__c = Date.today().addDays(-1),
            X6sense_Account_6QA_Start_Date__c = Date.today().addDays(-2),
            X6sense_Account_Buying_Stage__c = 'Definitely buying',
            X6sense_Account_Intent_Score__c = 123,
            X6sense_Account_Profile_Fit__c = 'Nice fit',
            X6sense_Account_Reach_Score__c = 456,
            X6Sense_Segment_Name__c = 'Nice segment my friend',
            X6sense_Stage_Awareness__c = Date.today().addDays(-4),
            X6sense_Stage_Consideration__c = Date.today().addDays(-3),
            X6sense_Stage_Decision__c = Date.today().addDays(-2),
            X6sense_Stage_Purchase__c = Date.today().addDays(-1),
            Named_Account__c = true,
            Named_Account_Tier__c = 'Tier 1'
        );
    }

    @isTest
    static void testStageZeroOppCreation() {
        Account account = [
            SELECT Id, X6QA__c
            FROM Account
            WHERE Name = 'StageZeroOppInitializerTest'
        ];
        account.X6QA__c = true;
        Id accountId = account.Id;

        update account;

        List<String> fields = new List<String>{
            'X6QA__c',
            'X6sense_Account_6QA_End_Date__c',
            'X6sense_Account_6QA_Start_Date__c',
            'X6sense_Account_Buying_Stage__c',
            'X6sense_Account_Intent_Score__c',
            'X6sense_Account_Profile_Fit__c',
            'X6sense_Account_Reach_Score__c',
            'X6Sense_Segment_Name__c',
            'X6sense_Stage_Awareness__c',
            'X6sense_Stage_Consideration__c',
            'X6sense_Stage_Decision__c',
            'X6sense_Stage_Purchase__c',
            'Named_Account__c',
            'Named_Account_Tier__c'
        };

        List<Opportunity> opps = Database.query(
            'SELECT Id, Account_Stage_at_Creation__c, ' +
            String.join(fields, ', ') +
            ' FROM Opportunity WHERE AccountId = :accountId AND RecordType.Name =\'Lead\''
        );

        System.assertEquals(
            1,
            opps.size(),
            'Incorrect number of Opportunity records created.'
        );

        account = (Account) Database.query(
            'SELECT Id, Account_Stage__c, ' +
            String.join(fields, ', ') +
            ' FROM Account WHERE Id = :accountId'
        );

        System.assertEquals(
            account.Account_Stage__c,
            opps[0].Account_Stage_at_Creation__c,
            'Account Stage at Creation not correctly set on Opportunity'
        );
        for (String field : fields) {
            Object expected = account.get(field);
            Object actual = opps[0].get(field);
            System.assertEquals(
                expected,
                actual,
                'Incorrect value set on Opportunity for field: ' + field
            );
        }
    }
}