unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/First_Response__c.field-meta.xml
<CustomField>
    <fullName>First_Response__c</fullName>
    <description>It stores the First response date and time and triggers the auto-complete of the milestone.</description>
    <label>First Response</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/CaseUpdateMilestoneCompleteHandlerTest.cls
@isTest
public with sharing class CaseUpdateMilestoneCompleteHandlerTest {
  @TestSetup
  static void createDataSet() {
    Id accountRecordType = RecordTypeUtility.getid(
      Account.getSObjectType(),
      'Customer'
    );

    SlaProcess slaProcessesId = [
      SELECT Id, Description, Name
      FROM SlaProcess
      WHERE
        SObjectType = 'Case'
        AND IsActive = true
        AND IsVersionDefault = true
        AND Name = 'Platinum'
    ];

    List<Account> accounts = new List<Account>();
    for (Integer i = 0; i < 3; i++) {
      Account account = new Account();
      account.Name = 'TESTSLA' + i;
      account.RecordTypeId = accountRecordType;
      account.Account_Stage__c = 'Prospect';

      accounts.add(account);
    }

    insert accounts;

    List<Contact> contactsAccount = new List<Contact>();
    for (Account acc : accounts) {
      Contact contact = new Contact();
      String email = 'test' + acc.Name;
      contact.FirstName = 'test';
      contact.LastName = 'test';
      contact.AccountId = acc.Id;
      contact.Email = email + '@gmail.com';
      contactsAccount.add(contact);
    }

    insert contactsAccount;

    List<Entitlement> accountEntitlments = new List<Entitlement>();
    for (Account account : accounts) {
      Entitlement accountEntitlement = new Entitlement();
      accountEntitlement.AccountId = account.Id;

      accountEntitlement.SlaProcessId = slaProcessesId.Id;
      accountEntitlement.Name = 'TestSLA ' + account.Name;
      accountEntitlement.StartDate = System.today();
      accountEntitlement.EndDate = System.today().addDays(20);

      accountEntitlments.add(accountEntitlement);
    }

    insert accountEntitlments;

    Id technicalSupportRecordType = RecordTypeUtility.getid(
      Case.getSObjectType(),
      'Technical Support'
    );

    List<Case> caseList = new List<Case>();
    for (Contact contact : contactsAccount) {
      Case cases = new Case();
      cases.ContactId = contact.Id;
      cases.RecordTypeId = technicalSupportRecordType;
      cases.Priority = 'P1 - Critical';
      cases.Subject = 'TEST SLA';
      cases.Origin = 'Email';

      caseList.add(cases);
    }
    insert caseList;
  }

  @isTest
  static void testMilestonesOnCases() {
    List<Case> caseList = [
      SELECT Id, Subject, ContactId
      FROM CASE
      WHERE Subject = 'TEST SLA'
    ];

    Test.startTest();
    for (Case cases : caseList) {
      cases.First_Response__c = System.now();
    }
    update caseList;
    Test.stopTest();

    List<CaseMilestone> caseMilestones = [
      SELECT Id, MilestoneTypeId, CaseId, IsCompleted
      FROM CaseMilestone
      WHERE CaseId IN :caseList
    ];

    for (CaseMilestone cm : caseMilestones) {
      System.assertEquals(
        true,
        cm.IsCompleted,
        'Not all milestones have bene completed'
      );
    }
  }
}