unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pending_Merge_Review__c.field-meta.xml
<CustomField>
    <fullName>Pending_Merge_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by the SFDC Team during the instance migration to facilitate merging of account records.  When multiple Customer Accounts with an Account Stage of &quot;Customer&quot; are identified, the business will need to review to determine the primary record for merging.  Setting this value to true will skip any affected records during the scheduled merge process.</description>
    <label>Pending Merge Review</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/classes/AccountMergerQueueable.cls
public with sharing class AccountMergerQueueable implements Queueable {
    Boolean needsRequeue = false;
    Boolean hasMultipleCustomerAccounts = false;
    Account primary;
    List<Account> secondaries = new List<Account>();

    public void execute(QueueableContext ctx) {
        String dunsNumber = getDunsNumber();

        if (dunsNumber == null) {
            return;
        }

        processAccounts(dunsNumber);

        Boolean isSuccess = MergeProcessor.processMerge(primary, secondaries);
        if (isSuccess && needsRequeue) {
            System.enqueueJob(new AccountMergerQueueable());
        }
    }

    private void processAccounts(String dunsNumber) {
        String query = MergeProcessor.getSelectStarQuery(
            Account.getSObjectType()
        );
        query += ' WHERE D_U_N_S_Number__c = :dunsNumber AND Pending_Merge_Review__c = FALSE ORDER BY Account_Stage__c DESC LIMIT 3';

        List<Account> accounts = Database.query(query);
        needsRequeue = accounts.size() > 3;

        primary = accounts[0];
        if (accounts[1].Account_Stage__c == 'Customer') {
            setPendingReview(dunsNumber);
            return;
        }

        secondaries.add(accounts[1]);
        if (accounts.size() > 2) {
            secondaries.add(accounts[2]);
        }

        copySecondariesValues();
    }

    private void copySecondariesValues() {
        List<String> fields = MergeProcessor.getQueryFields(
            Account.getSObjectType()
        );
        for (String field : fields) {
            if (primary.get(field) == null) {
                for (Account secondary : secondaries) {
                    if (secondary.get(field) != null) {
                        primary.put(field, secondary.get(field));
                        break;
                    }
                }
            }
        }
    }

    private void setPendingReview(String dunsNumber) {
        List<Account> accounts = [
            SELECT Id, Pending_Merge_Review__c
            FROM Account
            WHERE D_U_N_S_Number__c = :dunsNumber
        ];
        for (Account account : accounts) {
            account.Pending_Merge_Review__c = true;
        }
        update accounts;
    }

    private String getDunsNumber() {
        List<AggregateResult> aggregateResults = [
            SELECT D_U_N_S_Number__c
            FROM Account
            WHERE Pending_Merge_Review__c = FALSE
            GROUP BY D_U_N_S_Number__c
            HAVING COUNT(Id) > 1
        ];

        if (aggregateResults.isEmpty()) {
            return null;
        }

        needsRequeue = aggregateResults.size() > 1;

        return (String) aggregateResults[0].get('D_U_N_S_Number__c');
    }
}