unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Named_Account_Tier__c</fullName>
    <label>Named Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_6QA_End_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_End_Date__c</fullName>
    <label>6sense Account 6QA End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_6QA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_Start_Date__c</fullName>
    <label>6sense Account 6QA Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_Reach_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Reach_Score__c</fullName>
    <label>6sense Account Reach Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Awareness__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Awareness__c</fullName>
    <label>6sense Stage – Awareness</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Consideration__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Consideration__c</fullName>
    <label>6sense Stage – Consideration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Decision__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Decision__c</fullName>
    <label>6sense Stage – Decision</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Purchase__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Purchase__c</fullName>
    <label>6sense Stage – Purchase</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Account_Stage_at_Creation__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage_at_Creation__c</fullName>
    <label>Account Stage at Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Named_Account_Tier__c</fullName>
    <label>Named Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_6QA_End_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_End_Date__c</fullName>
    <label>6sense Account 6QA End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_6QA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_Start_Date__c</fullName>
    <label>6sense Account 6QA Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Buying_Stage__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Buying_Stage__c</fullName>
    <label>6sense Account Buying Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Intent_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Intent_Score__c</fullName>
    <label>6sense Account Intent Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Profile_Fit__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Profile_Fit__c</fullName>
    <label>6sense Account Profile Fit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Reach_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Reach_Score__c</fullName>
    <label>6sense Account Reach Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6Sense_Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>X6Sense_Segment_Name__c</fullName>
    <label>6Sense Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Awareness__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Awareness__c</fullName>
    <label>6sense Stage – Awareness</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Consideration__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Consideration__c</fullName>
    <label>6sense Stage – Consideration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Decision__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Decision__c</fullName>
    <label>6sense Stage – Decision</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Purchase__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Purchase__c</fullName>
    <label>6sense Stage – Purchase</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/classes/StageZeroOppInitializer.cls
public with sharing class StageZeroOppInitializer extends DomainLogicHandler {
    private Id leadRecordTypeId = RecordTypeUtility.getId(
        Opportunity.getSObjectType(),
        'Lead'
    );
    private List<Id> accountIds = new List<Id>();
    private List<Opportunity> qualifiedOpps = new List<Opportunity>();
    @TestVisible
    private List<String> fields = new List<String>{
        'X6QA__c',
        'X6sense_Account_6QA_End_Date__c',
        'X6sense_Account_6QA_Start_Date__c',
        'X6sense_Account_Buying_Stage__c',
        'X6sense_Account_Intent_Score__c',
        'X6sense_Account_Profile_Fit__c',
        'X6sense_Account_Reach_Score__c',
        'X6Sense_Segment_Name__c',
        'X6sense_Stage_Awareness__c',
        'X6sense_Stage_Consideration__c',
        'X6sense_Stage_Decision__c',
        'X6sense_Stage_Purchase__c',
        'Named_Account__c',
        'Named_Account_Tier__c'
    };

    public override void check(SObject newObj) {
        Opportunity newOpp = (Opportunity) newObj;
        if (isQualified(newOpp)) {
            accountIds.add(newOpp.AccountId);
            qualifiedOpps.add(newOpp);
        }
    }

    public override void processRecords() {
        Map<Id, Account> accounts = new Map<Id, Account>(
            (List<Account>) Database.query(getQueryString())
        );
        for (Opportunity opp : qualifiedOpps) {
            Account account = accounts.get(opp.AccountId);
            setValues(opp, account);
        }
    }

    private Boolean isQualified(Opportunity newOpp) {
        return newOpp.RecordTypeId == leadRecordTypeId;
    }

    private String getQueryString() {
        return 'SELECT Id, Account_Stage__c, ' +
            String.join(fields, ', ') +
            ' FROM Account WHERE Id IN :accountIds';
    }

    private void setValues(Opportunity opp, Account account) {
        for (String field : fields) {
            opp.put(field, account.get(field));
            opp.Account_Stage_at_Creation__c = (String) account.get(
                'Account_Stage__c'
            );
        }
    }
}