unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Support_package__c.field-meta.xml
<CustomField>
    <fullName>Support_package__c</fullName>
    <label>Support package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Platinum+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/classes/AccountCreateAssignDefaultEntitlements.cls
public with sharing class AccountCreateAssignDefaultEntitlements extends DomainLogicHandler {
  List<Account> accountSet = new List<Account>();

  public override void check(SObject newObject) {
    Id accountRecordType = RecordTypeUtility.getid(
      Account.getSObjectType(),
      'Customer'
    );

    Account accountRecord = (Account) newObject;
    if (
      (accountRecord.RecordTypeId == accountRecordType) &&
      (accountRecord.Account_Stage__c == 'Prospect')
    ) {
      accountSet.add(accountRecord);
    }
  }

  public override void check(SObject newObj, SObject oldObj) {
    Account newAccount = (Account) newObj;
    Account oldAccount = (Account) oldObj;

    Id accountRecordType = RecordTypeUtility.getid(
      Account.getSObjectType(),
      'Customer'
    );

    if (
      (newAccount.RecordTypeId == accountRecordType) &&
      (newAccount.Account_Stage__c != oldAccount.Account_Stage__c) &&
      (newAccount.Account_Stage__c == 'Former')
    ) {
      accountSet.add(newAccount);
    }
  }

  public override void processRecords() {
    List<Entitlement> entitlementSet = new List<Entitlement>();
    List<Entitlement> entlToDeactivate = new List<Entitlement>();

    if (accountSet.size() > 0) {
      entlToDeactivate = [
        SELECT id, AccountId
        FROM Entitlement
        WHERE AccountId IN :accountSet
      ];
      System.debug('AccountSET: ' + accountSet);
      System.debug('EntToDeactivate: ' + entlToDeactivate);

      for (Entitlement entl : entlToDeactivate) {
        entl.EndDate = System.today().addDays(-1);
      }

      update entlToDeactivate;

      SlaProcess goldSlaProcessId = [
        SELECT Id
        FROM SlaProcess
        WHERE Name = 'Gold'
      ];
      for (Account accRecord : accountSet) {
        Entitlement supportPackageEntitlement = new Entitlement();

        accRecord.Support_package__c = 'Gold';

        supportPackageEntitlement.AccountId = accRecord.Id;
        supportPackageEntitlement.SlaProcessId = goldSlaProcessId.Id;
        supportPackageEntitlement.StartDate = System.today();
        supportPackageEntitlement.Name = 'Default - Gold Support';
        entitlementSet.add(supportPackageEntitlement);
      }

      insert entitlementSet;
      update accountSet;
    }
  }
}