unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Convert_to_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Convert_to_Pipeline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convert to Pipeline</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/OpportunityPipelineConverter.cls
public with sharing class OpportunityPipelineConverter extends DomainLogicHandler {
    List<Opportunity> qualifiedOpps = new List<Opportunity>();
    List<Id> accountIds = new List<Id>();

    public override void check(SObject newObj, SObject oldObj) {
        Opportunity newOpp = (Opportunity) newObj;
        Opportunity oldOpp = (Opportunity) oldObj;
        if (isQualified(newOpp, oldOpp)) {
            qualifiedOpps.add(newOpp);
            accountIds.add(newOpp.AccountId);
        }
    }

    public override void processRecords() {
        if (!accountIds.isEmpty()) {
            Map<Id, Account> accounts = new Map<Id, Account>(
                [
                    SELECT Id, Account_Stage__c
                    FROM Account
                    WHERE Id IN :accountIds
                ]
            );
            for (Opportunity opp : qualifiedOpps) {
                String accountStage = accounts.get(opp.AccountId)
                    .Account_Stage__c;
                switch on accountStage {
                    when 'Customer' {
                        opp.RecordTypeId = RecordTypeUtility.getId(
                            Opportunity.getSObjectType(),
                            'Add-On'
                        );
                    }
                    when else {
                        opp.RecordTypeId = RecordTypeUtility.getId(
                            Opportunity.getSObjectType(),
                            'New Business'
                        );
                    }
                }
                opp.StageName = '1 - Discovery';
            }
        }
    }

    private Boolean isQualified(Opportunity newOpp, Opportunity oldOpp) {
        return newOpp.Convert_to_Pipeline__c != oldOpp.Convert_to_Pipeline__c &&
            newOpp.Convert_to_Pipeline__c;
    }
}