unpackaged/main/default/objects/Account/fields/Keep_Disqualified__c.field-meta.xml
<CustomField>
    <fullName>Keep_Disqualified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Disqualified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Competitor.recordType-meta.xml
<RecordType>
    <fullName>Competitor</fullName>
    <active>true</active>
    <label>Competitor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>For Partner accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Qualified_Out_Reason__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Out_Reason__c</fullName>
    <label>Qualified Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Already a customer</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Could not engage</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Existing solution</fullName>
            </value>
            <value>
                <fullName>Never a fit</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>No champion</fullName>
            </value>
            <value>
                <fullName>No need</fullName>
            </value>
            <value>
                <fullName>No show</fullName>
            </value>
            <value>
                <fullName>Not a business</fullName>
            </value>
            <value>
                <fullName>Not a fit</fullName>
            </value>
            <value>
                <fullName>Not a fit now</fullName>
            </value>
            <value>
                <fullName>Not right time</fullName>
            </value>
            <value>
                <fullName>Out of business</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Stopped communicating</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AccountDisqualifier.cls
public with sharing class AccountDisqualifier {
    public static Boolean isReasonQualified(Opportunity opp) {
        List<String> qualifiedReasons = new List<String>{
            'Not a business',
            'Out of business',
            'Never a fit',
            'Competitor',
            'Vendor',
            'Partner'
        };

        return qualifiedReasons.contains(opp.Qualified_Out_Reason__c);
    }

    public static void process(Map<Id, String> accountIdDisqualifications) {
        if (System.isFuture() || System.isBatch()) {
            List<Account> accounts = new List<Account>();
            for (Id accountId : accountIdDisqualifications.keySet()) {
                Account account = new Account(
                    Id = accountId,
                    Keep_Disqualified__c = true
                );

                String disqualification = accountIdDisqualifications.get(
                    accountId
                );
                switch on disqualification {
                    when 'Competitor' {
                        account.RecordTypeId = RecordTypeUtility.getId(
                            Account.getSObjectType(),
                            'Competitor'
                        );
                    }
                    when 'Vendor' {
                        account.RecordTypeId = RecordTypeUtility.getId(
                            Account.getSObjectType(),
                            'Vendor'
                        );
                    }
                    when 'Partner' {
                        account.RecordTypeId = RecordTypeUtility.getId(
                            Account.getSObjectType(),
                            'Partner'
                        );
                    }
                }
                accounts.add(account);
            }

            try {
                update accounts;
            } catch (Exception e) {
                ExceptionHandler.process(e, 'AccountDisqualifier');
            }
            return;
        }

        processAsync(accountIdDisqualifications);
    }

    @future
    public static void processAsync(
        Map<Id, String> accountIdDisqualifications
    ) {
        process(accountIdDisqualifications);
    }
}