unpackaged/main/default/objects/Account/fields/Keep_Disqualified__c.field-meta.xml
<CustomField>
    <fullName>Keep_Disqualified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Disqualified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Competitor.recordType-meta.xml
<RecordType>
    <fullName>Competitor</fullName>
    <active>true</active>
    <label>Competitor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>For Partner accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Qualified_Out_Reason__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Out_Reason__c</fullName>
    <label>Qualified Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Already a customer</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Could not engage</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Existing solution</fullName>
            </value>
            <value>
                <fullName>Never a fit</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>No champion</fullName>
            </value>
            <value>
                <fullName>No need</fullName>
            </value>
            <value>
                <fullName>No show</fullName>
            </value>
            <value>
                <fullName>Not a business</fullName>
            </value>
            <value>
                <fullName>Not a fit</fullName>
            </value>
            <value>
                <fullName>Not a fit now</fullName>
            </value>
            <value>
                <fullName>Not right time</fullName>
            </value>
            <value>
                <fullName>Out of business</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Stopped communicating</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/classes/OpportunityDisqualificationHandlerTest.cls
@isTest
public with sharing class OpportunityDisqualificationHandlerTest {
    private static List<PicklistEntry> qualifiedOutReasons = Opportunity.Qualified_Out_Reason__c.getDescribe()
        .getPicklistValues();

    @TestSetup
    static void makeData() {
        List<Opportunity> opps = OpportunityTestFactory.getStageZeroOpps(
            qualifiedOutReasons.size()
        );

        insert opps;

        User bdr = TestUserProvisioner.getNewUser();
        insert bdr;

        List<AccountTeamMember> teamMembers = new List<AccountTeamMember>();
        for (Opportunity opp : opps) {
            teamMembers.add(
                new AccountTeamMember(
                    UserId = bdr.Id,
                    TeamMemberRole = 'Business Development Rep',
                    AccountId = opp.AccountId
                )
            );
        }
        insert teamMembers;

        Account namedAccount = new Account(
            Id = opps[0].AccountId,
            Named_Account__c = true
        );
        update namedAccount;
    }

    @isTest
    private static void testCleanAccountTeam() {
        List<Id> accountIds = new List<Id>();
        List<Opportunity> opps = [
            SELECT Id, AccountId, StageName
            FROM Opportunity
            WHERE RecordType.Name = 'Lead' AND IsClosed = FALSE
            LIMIT :qualifiedOutReasons.size()
        ];
        for (Integer i = 0; i < qualifiedOutReasons.size(); i++) {
            opps[i].StageName = '0 - Disqualified';
            opps[i].Qualified_Out_Reason__c = qualifiedOutReasons[i].getValue();
            accountIds.add(opps[i].AccountId);
        }

        Test.startTest();

        update opps;

        Test.stopTest();

        List<Account> accounts = [
            SELECT Id, Named_Account__c, (SELECT Id FROM AccountTeamMembers)
            FROM Account
            WHERE Id IN :accountIds
        ];
        for (Account account : accounts) {
            Boolean expected = account.Named_Account__c;
            System.assertEquals(
                expected,
                !account.AccountTeamMembers.isEmpty(),
                'Account Team Members were incorrectly processed.'
            );
        }
    }

    @isTest
    private static void testKeepAccountDisqualified() {
        List<Opportunity> opps = [
            SELECT Id, StageName, Qualified_Out_Reason__c
            FROM Opportunity
            WHERE RecordType.Name = 'Lead' AND IsClosed = FALSE
        ];
        for (Integer i = 0; i < opps.size(); i++) {
            opps[i].StageName = '0 - Disqualified';
            opps[i].Qualified_Out_Reason__c = qualifiedOutReasons[i].getValue();
        }

        Test.startTest();

        update opps;

        Test.stopTest();

        List<Log__c> logs = [SELECT Id, Text__c FROM Log__c];
        System.assert(true, logs.isEmpty());

        List<String> qualifiedReasons = new List<String>{
            'Not a business',
            'Out of business',
            'Never a fit',
            'Competitor',
            'Vendor',
            'Partner'
        };

        opps = [
            SELECT Id, Account.Keep_Disqualified__c, Qualified_Out_Reason__c
            FROM Opportunity
            WHERE RecordType.Name = 'Lead' AND StageName = '0 - Disqualified'
        ];
        for (Opportunity opp : opps) {
            System.assertEquals(
                qualifiedReasons.contains(opp.Qualified_Out_Reason__c),
                opp.Account.Keep_Disqualified__c,
                'The related Account\'s Keep Disqualified field was not correctly set for Qualified Out Reason: ' +
                opp.Qualified_Out_Reason__c
            );
        }
    }
}