unpackaged/main/default/objects/Account/fields/X6sense_Stage_Awareness__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Awareness__c</fullName>
    <label>6sense Stage – Awareness</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Consideration__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Consideration__c</fullName>
    <label>6sense Stage – Consideration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Decision__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Decision__c</fullName>
    <label>6sense Stage – Decision</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Purchase__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Purchase__c</fullName>
    <label>6sense Stage – Purchase</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/AccountBuyingStageFieldStamper.cls
/**
 * Tests for this class are found in AccountStamperTest
 */
public with sharing class AccountBuyingStageFieldStamper extends FieldStamper {
    public override void stamp(SObject sobj) {
        Account account = (Account) sobj;
        switch on account.X6sense_Account_Buying_Stage__c {
            when 'Awareness' {
                account.X6sense_Stage_Awareness__c = Date.today();
            }
            when 'Consideration' {
                account.X6sense_Stage_Consideration__c = Date.today();
            }
            when 'Decision' {
                account.X6sense_Stage_Decision__c = Date.today();
            }
            when 'Purchase' {
                account.X6sense_Stage_Purchase__c = Date.today();
            }
        }
    }
}