unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Addressable_Business_Problems__c.field-meta.xml
<CustomField>
    <fullName>Addressable_Business_Problems__c</fullName>
    <inlineHelpText>What Business Problem(s) or Opportunities are we addressing?</inlineHelpText>
    <label>Addressable Business Problems</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Anticipated_Roadblocks_Challenges__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Roadblocks_Challenges__c</fullName>
    <inlineHelpText>Are there any anticipated roadblocks or challenges during the onboarding period?</inlineHelpText>
    <label>Anticipated Roadblocks/Challenges</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Budget_Source__c.field-meta.xml
<CustomField>
    <fullName>Budget_Source__c</fullName>
    <label>Budget Source</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Competitors__c.field-meta.xml
<CustomField>
    <fullName>Competitors__c</fullName>
    <description>Who are we competing with for this deal?</description>
    <inlineHelpText>Who are we competing with for this deal?</inlineHelpText>
    <label>Competitors</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Akamai</fullName>
            </value>
            <value>
                <fullName>Amazon Web Services</fullName>
            </value>
            <value>
                <fullName>Bitmovin</fullName>
            </value>
            <value>
                <fullName>Brandlive</fullName>
            </value>
            <value>
                <fullName>CDNetworks</fullName>
            </value>
            <value>
                <fullName>Comcast Technology Solutions (thePlatform or CTS)</fullName>
            </value>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>DaCast (Vzaar)</fullName>
            </value>
            <value>
                <fullName>Dailymotion</fullName>
            </value>
            <value>
                <fullName>Deltatre</fullName>
            </value>
            <value>
                <fullName>DIY</fullName>
            </value>
            <value>
                <fullName>Dubb</fullName>
            </value>
            <value>
                <fullName>Encoding.com</fullName>
            </value>
            <value>
                <fullName>Endeavor (NeuLion)</fullName>
            </value>
            <value>
                <fullName>Grabyo</fullName>
            </value>
            <value>
                <fullName>Hopin</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>J-stream</fullName>
            </value>
            <value>
                <fullName>JW Player</fullName>
            </value>
            <value>
                <fullName>Kaltura</fullName>
            </value>
            <value>
                <fullName>Limelight Platform</fullName>
            </value>
            <value>
                <fullName>Mediastream</fullName>
            </value>
            <value>
                <fullName>Microsoft Stream</fullName>
            </value>
            <value>
                <fullName>Moving Image 24</fullName>
            </value>
            <value>
                <fullName>Muvi</fullName>
            </value>
            <value>
                <fullName>Mux</fullName>
            </value>
            <value>
                <fullName>On24</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Panopto</fullName>
            </value>
            <value>
                <fullName>Piksel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Customer_Business_Model__c</fullName>
    <inlineHelpText>What is the customer&#39;s business model?</inlineHelpText>
    <label>Customer Business Model</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Buying_Steps__c.field-meta.xml
<CustomField>
    <fullName>Customer_Buying_Steps__c</fullName>
    <inlineHelpText>What Buying Steps must the Customer go through?</inlineHelpText>
    <label>Customer Buying Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Expected_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Customer_Expected_Outcomes__c</fullName>
    <description>What Outcome(s) do they want to achieve and by When?</description>
    <label>Customer Expected Outcomes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Success_KPIs__c.field-meta.xml
<CustomField>
    <fullName>Customer_Success_KPIs__c</fullName>
    <inlineHelpText>How will the customer measure the success of their video implementation?</inlineHelpText>
    <label>Customer Success KPIs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <inlineHelpText>Confidence the deal will close in this quarter.</inlineHelpText>
    <label>Forecast</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Commit</fullName>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Importance_and_Priority__c.field-meta.xml
<CustomField>
    <fullName>Importance_and_Priority__c</fullName>
    <inlineHelpText>Who are they important to; is it a high Priority?</inlineHelpText>
    <label>Importance and Priority</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Integrations_Required__c.field-meta.xml
<CustomField>
    <fullName>Integrations_Required__c</fullName>
    <description>Are there any 3rd party or partner integrations to consider? (Accedo, Iris.TV, Google Analytics, CRM, etc...)</description>
    <inlineHelpText>Are there any 3rd party or partner integrations to consider? (Accedo, Iris.TV, Google Analytics, CRM, etc...)</inlineHelpText>
    <label>Integrations Required</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Email_s__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email_s__c</fullName>
    <description>List emails that should receive the invoice from billing. If there is more than one separate by comma.</description>
    <label>Invoice Email(s)</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Mutual_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Mutual_Action_Plan__c</fullName>
    <inlineHelpText>What is our Mutual Action Plan to turn the Opportunity into Revenue?</inlineHelpText>
    <label>Mutual Action Plan</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Proposal_Document__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Document__c</fullName>
    <inlineHelpText>Provide the URL to the google drive folder containing the document. If not applicable, please type &#39;N/A&#39;</inlineHelpText>
    <label>Proposal Document</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Qualified_Out_Reason__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Out_Reason__c</fullName>
    <label>Qualified Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Already a customer</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Could not engage</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Existing solution</fullName>
            </value>
            <value>
                <fullName>Never a fit</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>No champion</fullName>
            </value>
            <value>
                <fullName>No need</fullName>
            </value>
            <value>
                <fullName>No show</fullName>
            </value>
            <value>
                <fullName>Not a business</fullName>
            </value>
            <value>
                <fullName>Not a fit</fullName>
            </value>
            <value>
                <fullName>Not a fit now</fullName>
            </value>
            <value>
                <fullName>Not right time</fullName>
            </value>
            <value>
                <fullName>Out of business</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Stopped communicating</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Strategy_to_Win__c.field-meta.xml
<CustomField>
    <fullName>Sales_Strategy_to_Win__c</fullName>
    <inlineHelpText>Can we Win (provide more Value) and what is our Sales Strategy to beat it?</inlineHelpText>
    <label>Sales Strategy to Win</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Solution_Document__c.field-meta.xml
<CustomField>
    <fullName>Solution_Document__c</fullName>
    <description>For the SE to define the solution document. Used together with the &quot;Solution Complete&quot; field.</description>
    <label>Solution Document</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Targeted_Platforms__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Platforms__c</fullName>
    <inlineHelpText>What are the targeted platforms?</inlineHelpText>
    <label>Targeted Platforms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Apps</fullName>
            </value>
            <value>
                <fullName>Mobile Web</fullName>
            </value>
            <value>
                <fullName>OTT</fullName>
            </value>
            <value>
                <fullName>Smart TV</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Technical_Win__c.field-meta.xml
<CustomField>
    <fullName>Technical_Win__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For the SE to mark if the solution has been completed or not.</description>
    <label>Technical Win</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Value_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Value_Proposition__c</fullName>
    <inlineHelpText>What is our irresistible Value Proposition(s) that will compel the Customer to do a Deal quickly?</inlineHelpText>
    <label>Value Proposition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/OpportunityTestFactory.cls
@isTest
public with sharing class OpportunityTestFactory {
    private static Id newBusinessRecordTypeId = RecordTypeUtility.getId(
        Opportunity.getSObjectType(),
        'New Business'
    );
    private static Id leadRecordTypeId = RecordTypeUtility.getId(
        Opportunity.getSObjectType(),
        'Lead'
    );

    public static List<Opportunity> getStageZeroOpps(Integer count) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < count; i++) {
            accounts.add(
                new Account(
                    Name = 'OpportunityTestFactory Stage Zero ' +
                        String.valueOf(i + 1),
                    RecordTypeId = RecordTypeUtility.getId(
                        Account.getSObjectType(),
                        'Customer'
                    )
                )
            );
        }
        insert accounts;

        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < count; i++) {
            contacts.add(
                new Contact(
                    LastName = 'getStageZeroOpps' + String.valueOf(i),
                    Email = 'getStageZeroOpps' +
                        String.valueOf(i) +
                        '@example.com',
                    AccountId = accounts[i].Id
                )
            );
        }
        insert contacts;

        List<Opportunity> opps = new List<Opportunity>();
        for (Integer i = 0; i < count; i++) {
            opps.add(
                new Opportunity(
                    Name = 'Irrelevant',
                    RecordTypeId = leadRecordTypeId,
                    StageName = '0 - Meeting Pending',
                    AccountId = accounts[i].Id,
                    ContactId = contacts[i].Id,
                    CloseDate = Date.today().addDays(30),
                    Forecast__c = 'Omitted'
                )
            );
        }
        return opps;
    }

    public static Opportunity getStageZeroOpp() {
        return getStageZeroOpps(1)[0];
    }

    public static void disqualifyStageZeroOpp(Opportunity opp) {
        opp.StageName = '0 - Disqualified';
        opp.Qualified_Out_Reason__c = Opportunity.Qualified_Out_Reason__c.getDescribe()
                .getPicklistValues()[0]
            .getValue();
    }

    public static void setStage2(Opportunity opp) {
        createPrimaryQuote(opp.Id);
        opp.Customer_Business_Model__c = 'N/A';
        opp.Targeted_Platforms__c = 'Other';
        opp.Competitors__c = 'Other';
        opp.Importance_and_Priority__c = 'N/A';
        opp.StageName = '2 - Demo';
    }

    public static void setStage3(Opportunity opp) {
        opp.Addressable_Business_Problems__c = 'N/A';
        opp.Customer_Expected_Outcomes__c = 'N/A';
        opp.Integrations_Required__c = 'N/A';
        opp.Sales_Strategy_to_Win__c = 'N/A';
        opp.Value_Proposition__c = 'N/A';
        opp.Budget_Source__c = 'N/A';
        opp.StageName = '3 - Solution Design & Evaluation';
    }

    public static void setStage4(Opportunity opp) {
        opp.Customer_Buying_Steps__c = 'N/A';
        opp.Mutual_Action_Plan__c = 'N/A';
        opp.Proposal_Document__c = 'http://example.com';
        opp.Solution_Document__c = 'http://example.com';
        opp.Technical_Win__c = true;
        opp.Customer_Success_KPIs__c = 'N/A';
        opp.StageName = '4 - Negotiation';
    }

    public static Opportunity getStage1Opp(Id accountId, Id recordTypeId) {
        Contact contact = new Contact(
            LastName = 'getStage1Opp',
            Email = GuidUtility.generateGuid() + '@example.com',
            AccountId = accountId
        );
        insert contact;
        return getStubOpp(contact, recordTypeId);
    }

    public static Opportunity getStage2Opp(Id accountId, Id recordTypeId) {
        Opportunity opp = getStage1Opp(accountId, recordTypeId);
        insert opp;
        setStage2(opp);
        return opp;
    }

    public static Opportunity getStage3Opp(Id accountId, Id recordTypeId) {
        Opportunity opp = getStage2Opp(accountId, recordTypeId);
        setStage3(opp);
        return opp;
    }

    public static Opportunity getStage4Opp(Id accountId, Id recordTypeId) {
        Opportunity opp = getStage3Opp(accountId, recordTypeId);
        setStage4(opp);
        return opp;
    }

    public static Opportunity getStage1Opp(Id accountId) {
        return getStage1Opp(accountId, newBusinessRecordTypeId);
    }

    public static Opportunity getStage2Opp(Id accountId) {
        return getStage2Opp(accountId, newBusinessRecordTypeId);
    }

    public static Opportunity getStage3Opp(Id accountId) {
        return getStage3Opp(accountId, newBusinessRecordTypeId);
    }

    public static Opportunity getStage4Opp(Id accountId) {
        return getStage4Opp(accountId, newBusinessRecordTypeId);
    }

    public static void closeWin(Opportunity opp) {
        opp.StageName = 'Closed Won';
    }

    private static void createPrimaryQuote(Id opportunityId) {
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Status__c = 'Draft',
            SBQQ__Opportunity2__c = opportunityId,
            SBQQ__Primary__c = true,
            SBQQ__StartDate__c = Date.today(),
            SBQQ__PricebookId__c = Test.getStandardPricebookId()
        );
        insert quote;
    }

    private static Opportunity getStubOpp(Contact contact, Id recordTypeId) {
        return new Opportunity(
            Name = 'OpportunityStageAccountHandlerTest',
            AccountId = contact.AccountId,
            ContactId = contact.Id,
            StageName = '1 - Discovery',
            CloseDate = System.today(),
            LeadSource = 'Other',
            RecordTypeId = recordTypeId,
            Solution_Document__c = 'http://www.google.com',
            Anticipated_Roadblocks_Challenges__c = 'OpportunityTestFactory',
            Invoice_Email_s__c = 'OpportunityTestFactory@OpportunityTestFactory.com'
        );
    }
}