unpackaged/main/default/objects/Lead/fields/n2de__Is_rejected__c.field-meta.xml
<CustomField>
    <fullName>n2de__Is_rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
                <default>true</default>
                <label>Name</label>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
                <isActive>false</isActive>
                <label>Buyer</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Connected</fullName>
                <isActive>false</isActive>
                <label>Connected</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>MQL</fullName>
                <isActive>false</isActive>
                <label>MQL</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospecting</fullName>
                <isActive>false</isActive>
                <label>Prospecting</label>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
            <value>
                <fullName>Release from qualifying</fullName>
                <isActive>false</isActive>
                <label>Release from qualifying</label>
            </value>
            <value>
                <fullName>Relevant</fullName>
                <isActive>false</isActive>
                <label>Relevant</label>
            </value>
            <value>
                <fullName>SAL</fullName>
                <isActive>false</isActive>
                <label>SAL</label>
            </value>
            <value>
                <fullName>SQL</fullName>
                <isActive>false</isActive>
                <label>SQL</label>
            </value>
            <value>
                <fullName>Target</fullName>
                <isActive>false</isActive>
                <label>Target</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LeadStamper.cls
public with sharing class LeadStamper extends DomainLogicHandler {
    FieldStamperUtility stamper = new FieldStamperUtility(
        new Map<SObjectField, FieldStamper>{
            Lead.Stage__c => new LeadStageFieldStamper(),
            Lead.n2de__Is_rejected__c => new LeadRejectedFieldStamper()
        }
    );

    public override void check(SObject newObj) {
        stamper.qualifyRecord(newObj);
    }

    public override void check(SObject newObj, SObject oldObj) {
        stamper.qualifyRecord(newObj, oldObj);
    }

    public override void processRecords() {
        stamper.processStampers();
    }
}