unpackaged/main/default/objects/Lead/fields/n2de__Is_rejected__c.field-meta.xml
<CustomField>
    <fullName>n2de__Is_rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <label>Rejected Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Reason__c</fullName>
    <label>Rejected Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rejected_Reasons</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
                <default>true</default>
                <label>Name</label>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
                <isActive>false</isActive>
                <label>Buyer</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
                <isActive>false</isActive>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Connected</fullName>
                <isActive>false</isActive>
                <label>Connected</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>MQL</fullName>
                <isActive>false</isActive>
                <label>MQL</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospecting</fullName>
                <isActive>false</isActive>
                <label>Prospecting</label>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
            <value>
                <fullName>Release from qualifying</fullName>
                <isActive>false</isActive>
                <label>Release from qualifying</label>
            </value>
            <value>
                <fullName>Relevant</fullName>
                <isActive>false</isActive>
                <label>Relevant</label>
            </value>
            <value>
                <fullName>SAL</fullName>
                <isActive>false</isActive>
                <label>SAL</label>
            </value>
            <value>
                <fullName>SQL</fullName>
                <isActive>false</isActive>
                <label>SQL</label>
            </value>
            <value>
                <fullName>Target</fullName>
                <isActive>false</isActive>
                <label>Target</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Stage_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_Date__c</fullName>
    <label>Stage Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/LeadStamperTest.cls
@isTest
public with sharing class LeadStamperTest {
    @isTest
    private static void testStamp() {
        List<PicklistEntry> stages = Lead.Stage__c.getDescribe()
            .getPicklistValues();
        Lead testLead = new Lead(
            LastName = 'LeadStamperTest',
            Company = 'Tester',
            Stage__c = stages[0].getValue(),
            Email = 'testStamp@LeadStamperTest.com'
        );
        insert testLead;

        testLead = [
            SELECT
                Id,
                n2de__Is_rejected__c,
                Rejected_Reason__c,
                Stage_Date__c,
                Rejected_Date__c
            FROM Lead
            WHERE Id = :testLead.Id
        ];

        System.assertEquals(
            null,
            testLead.Rejected_Date__c,
            'Rejected Date was assigned at creation.'
        );
        System.assertEquals(
            Date.today(),
            testLead.Stage_Date__c,
            'Stage Date not set correctly.'
        );

        testLead.n2de__Is_rejected__c = true;
        testLead.Rejected_Reason__c = Lead.Rejected_Reason__c.getDescribe()
                .getPicklistValues()[0]
            .getValue();
        update testLead;

        testLead = [
            SELECT Id, Rejected_Date__c
            FROM Lead
            WHERE Id = :testLead.Id
        ];
        System.assertEquals(
            Date.today(),
            testLead.Rejected_Date__c,
            'Rejected Date not set correctly.'
        );
    }
}