unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Has_Legal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Has_Legal_Notes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Legal Notes</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Initial_Term_Amount_Renew__c.field-meta.xml
<CustomField>
    <fullName>Initial_Term_Amount_Renew__c</fullName>
    <label>Initial Term Amount (Renewables)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Initial_Term_Length__c.field-meta.xml
<CustomField>
    <fullName>Initial_Term_Length__c</fullName>
    <formula>IF(ISPICKVAL(SBQQ__Opportunity2__r.Contract_Type__c, &quot;Ramp Contract&quot;) &amp;&amp; SBQQ__SubscriptionTerm__c &gt; 12 &amp;&amp;  Outgoing_Document_Mandatory_Renewal__c, MOD(SBQQ__SubscriptionTerm__c, 12) + 12, IF(ISPICKVAL(SBQQ__Opportunity2__r.Contract_Type__c, &quot;Standard Term Contract&quot;) &amp;&amp; Outgoing_Document_Mandatory_Renewal__c, 12, SBQQ__SubscriptionTerm__c))</formula>
    <label>Initial Term Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Legal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Legal_Notes__c</fullName>
    <label>Legal Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Paperwork_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Paperwork_Product_Type__c</fullName>
    <formula>IF(Product_Type__c == &quot;Overage Rate&quot; || (SBQQ__ProductFamily__c == &quot;Rate Cards&quot; &amp;&amp; NOT(SBQQ__Bundle__c)), &quot;Overage Rate&quot;, IF(TEXT(SBQQ__SubscriptionType__c) == &quot;Renewable&quot;, &quot;Renewable&quot;, &quot;One-Time&quot; ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paperwork Product Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/QuotePaperworkHandler.cls
public with sharing class QuotePaperworkHandler extends DomainLogicHandler {
    List<SBQQ__Quote__c> workSet = new List<SBQQ__Quote__c>();

    public override void check(SObject newObj, SObject oldObj) {
        SBQQ__Quote__c quote = (SBQQ__Quote__c) newObj;

        quote.Has_Legal_Notes__c = quote.Legal_Notes__c != null;
        quote.SBQQ__WatermarkShown__c = quote.SBQQ__Status__c != 'Approved';
        workSet.add((SBQQ__Quote__c) newObj);
    }

    public override void processRecords() {
        Set<Id> quoteIds = new Set<Id>();

        for (SBQQ__Quote__c quote : workSet) {
            quoteIds.add(quote.Id);
        }

        Map<Id, SBQQ__Quote__c> currentQuotes = new Map<Id, SBQQ__Quote__c>(
            [
                SELECT
                    Id,
                    Initial_Term_Amount_Renew__c,
                    SBQQ__SubscriptionTerm__c,
                    Initial_Term_Length__c,
                    (
                        SELECT
                            Id,
                            Paperwork_Product_Type__c,
                            SBQQ__Product__r.No_Proration__c,
                            SBQQ__NetTotal__c
                        FROM SBQQ__LineItems__r
                    )
                FROM SBQQ__Quote__c
                WHERE Id IN :quoteIds
            ]
        );

        for(SBQQ__Quote__c quote : workSet) {
            SBQQ__Quote__c currentQuote = currentQuotes.get(quote.Id);
            Decimal initialTermTotal = 0.0;
            for(SBQQ__QuoteLine__c quoteLine : currentQuote.SBQQ__LineItems__r) {
                if(quoteLine.Paperwork_Product_Type__c == 'One-Time') {
                    continue;
                }

                if(quoteLine.SBQQ__Product__r.No_Proration__c) {
                    initialTermTotal += (Decimal)(quoteLine.SBQQ__NetTotal__c) / Math.floor(quote.SBQQ__SubscriptionTerm__c / quote.Initial_Term_Length__c).setScale(2);
                    continue;
                }

                if(quote.SBQQ__SubscriptionTerm__c < 12) {
                    initialTermTotal += (Decimal)((quoteLine.SBQQ__NetTotal__c / quote.SBQQ__SubscriptionTerm__c) * quote.Initial_Term_Length__c).setScale(2);
                } else {
                    initialTermTotal += (Decimal)((quoteLine.SBQQ__NetTotal__c / quote.SBQQ__SubscriptionTerm__c) * (quote.Initial_Term_Length__c - Math.mod((Integer)quote.Initial_Term_Length__c, 12))).setScale(2);
                }
            }

            quote.Initial_Term_Amount_Renew__c = initialTermTotal;
        }
    }
}