unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <description>Required for advanced approvals. This should be hidden from the page layout as it should be managed and synced with the CPQ status field</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/QuoteExtControllerTest.cls
//pulled from https://help.salesforce.com/s/articleView?id=sf.cpq_enable_aa.htm&type=5

@isTest
private class QuoteExtControllerTest {
    @TestSetup
    static void setup() {
        TestUserProvisioner provisioner = new TestUserProvisioner(
            UserInfo.getUserId()
        );
        provisioner.setLicenses(
            new List<String>{
                'SalesforceCPQ_CPQStandardPerm',
                'SalesforceCPQ_CPQAAPerm'
            }
        );
        provisioner.setPermissions(
            new List<String>{
                'Approvals_Global',
                'CPQ_Global',
                'SteelBrickCPQUser',
                'AdvancedApprovalsUser'
            }
        );
        provisioner.assignPermissions();
    }

    @IsTest
    static void testSubmit() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;

        System.runAs(new User(Id = UserInfo.getUserId())) {
            Test.startTest();

            QuoteExtController con = new QuoteExtController(
                new ApexPages.StandardController(quote)
            );
            con.onSubmit();

            Test.stopTest();
        }

        quote = [
            SELECT ApprovalStatus__c
            FROM SBQQ__Quote__c
            WHERE Id = :quote.Id
            LIMIT 1
        ];

        System.assertEquals('Approved', quote.ApprovalStatus__c);
    }

    @IsTest
    static void testRecall() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;

        System.runAs(new User(Id = UserInfo.getUserId())) {
            Test.startTest();

            QuoteExtController con = new QuoteExtController(
                new ApexPages.StandardController(quote)
            );
            con.onRecall();

            Test.stopTest();
        }
            
        quote = [
            SELECT ApprovalStatus__c
            FROM SBQQ__Quote__c
            WHERE Id = :quote.Id
            LIMIT 1
        ];

        System.assertEquals('Recalled', quote.ApprovalStatus__c);
    }
}