unpackaged/main/default/objects/Contact/fields/Email_Address_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_Domain__c</fullName>
    <formula>RIGHT(Email,  FIND(&quot;@&quot;, Email)-1 )</formula>
    <label>Email Address Domain</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ContactAccountEmailDomainHandler.cls
public with sharing class ContactAccountEmailDomainHandler extends DomainLogicHandler {
    private Map<Id, Contact> accountIdContactMap = new Map<Id, Contact>();

    public override void check(SObject newObj) {
        Contact newContact = (Contact) newObj;
        accountIdContactMap.put(newContact.AccountId, newContact);
    }

    public override void processRecords() {
        List<Account> accounts = [
            SELECT Id, Email_Domain_Name__c
            FROM Account
            WHERE
                Email_Domain_Name__c = NULL
                AND Id IN :accountIdContactMap.keySet()
        ];

        for (Account account : accounts) {
            account.Email_Domain_Name__c = accountIdContactMap.get(account.Id)
                .Email_Address_Domain__c;
        }
        
        update accounts;
    }
}