unpackaged/main/default/objects/Contact/fields/Is_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Is_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
                <isActive>false</isActive>
                <label>Buyer</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>MQL</fullName>
                <isActive>false</isActive>
                <label>MQL</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <isActive>false</isActive>
                <label>Opportunity</label>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
            <value>
                <fullName>Release from qualifying</fullName>
                <isActive>false</isActive>
                <label>Release from qualifying</label>
            </value>
            <value>
                <fullName>SAL</fullName>
                <isActive>false</isActive>
                <label>SAL</label>
            </value>
            <value>
                <fullName>SQL</fullName>
                <isActive>false</isActive>
                <label>SQL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ContactStamper.cls
public with sharing class ContactStamper extends DomainLogicHandler {
    FieldStamperUtility stamper = new FieldStamperUtility(
        new Map<SObjectField, FieldStamper>{
            Contact.Stage__c => new ContactStageFieldStamper(),
            Contact.Is_Rejected__c => new ContactRejectedFieldStamper()
        }
    );

    public override void check(SObject newObj) {
        stamper.qualifyRecord(newObj);
    }

    public override void check(SObject newObj, SObject oldObj) {
        stamper.qualifyRecord(newObj, oldObj);
    }

    public override void processRecords() {
        stamper.processStampers();
    }
}