unpackaged/main/default/objects/Contact/fields/Is_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Is_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <label>Rejected Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Reason__c</fullName>
    <label>Rejected Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rejected_Reasons</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
                <isActive>false</isActive>
                <label>Buyer</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>MQL</fullName>
                <isActive>false</isActive>
                <label>MQL</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <isActive>false</isActive>
                <label>Opportunity</label>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
            <value>
                <fullName>Release from qualifying</fullName>
                <isActive>false</isActive>
                <label>Release from qualifying</label>
            </value>
            <value>
                <fullName>SAL</fullName>
                <isActive>false</isActive>
                <label>SAL</label>
            </value>
            <value>
                <fullName>SQL</fullName>
                <isActive>false</isActive>
                <label>SQL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Stage_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_Date__c</fullName>
    <label>Stage Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ContactStamperTest.cls
@isTest
public with sharing class ContactStamperTest {
    @TestSetup
    private static void makeData() {
        insert new Account(Name = 'ContactStamperTest');
    }

    @isTest
    private static void testStamp() {
        Account account = [
            SELECT Id
            FROM Account
            WHERE Name = 'ContactStamperTest'
            LIMIT 1
        ];
        List<PicklistEntry> stages = Contact.Stage__c.getDescribe()
            .getPicklistValues();
        Contact testContact = new Contact(
            LastName = 'ContactStamperTest',
            FirstName = 'Test',
            AccountId = account.Id,
            Stage__c = stages[0].getValue(),
            Email = 'test@ContactStamperTest.com'
        );
        insert testContact;

        testContact = [
            SELECT Id, Stage_Date__c, Is_Rejected__c, Rejected_Date__c
            FROM Contact
            WHERE Id = :testContact.Id
        ];

        System.assertEquals(
            Date.today(),
            testContact.Stage_Date__c,
            'Stage Date not correctly set.'
        );
        System.assertEquals(
            null,
            testContact.Rejected_Date__c,
            'Rejected Date incorrectly set.'
        );

        testContact.Is_Rejected__c = true;
        testContact.Rejected_Reason__c = Contact.Rejected_Reason__c.getDescribe()
                .getPicklistValues()[0]
            .getValue();

        update testContact;

        testContact = [
            SELECT Id, Rejected_Date__c
            FROM Contact
            WHERE Id = :testContact.Id
        ];

        System.assertEquals(
            Date.today(),
            testContact.Rejected_Date__c,
            'Stage Date not correctly set.'
        );
    }
}