unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Brightcove Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account_Edition__c.field-meta.xml
<CustomField>
    <fullName>Account_Edition__c</fullName>
    <label>Account Edition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ENTERPRISE</fullName>
            </value>
            <value>
                <fullName>PRO</fullName>
            </value>
            <value>
                <fullName>BASIC</fullName>
            </value>
            <value>
                <fullName>EXPRESS_500</fullName>
            </value>
            <value>
                <fullName>EXPRESS_200</fullName>
            </value>
            <value>
                <fullName>EXPRESS_100</fullName>
            </value>
            <value>
                <fullName>EXPRESS_PROMO_39</fullName>
            </value>
            <value>
                <fullName>EXPRESS_PROMO_29</fullName>
            </value>
            <value>
                <fullName>EXPRESS_PROMO_5</fullName>
            </value>
            <value>
                <fullName>Express Retention $199 Conversion</fullName>
            </value>
            <value>
                <fullName>Express Retention $99 Conversion</fullName>
            </value>
            <value>
                <fullName>CORE</fullName>
            </value>
            <value>
                <fullName>PRO_I</fullName>
            </value>
            <value>
                <fullName>PRO_II</fullName>
            </value>
            <value>
                <fullName>PRO_III</fullName>
            </value>
            <value>
                <fullName>Pay-As-You-Go</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Traction</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Perform - Standard</fullName>
            </value>
            <value>
                <fullName>VMS_Starter_1_Monthly</fullName>
            </value>
            <value>
                <fullName>VMS_Starter_1_Annual</fullName>
            </value>
            <value>
                <fullName>VMS_Starter_2_Monthly</fullName>
            </value>
            <value>
                <fullName>VMS_Starter_2_Annual</fullName>
            </value>
            <value>
                <fullName>EVS_Sales_Starter_1_Monthly</fullName>
            </value>
            <value>
                <fullName>EVS_Sales_Starter_2_Monthly</fullName>
            </value>
            <value>
                <fullName>EVS_Sales_Starter_1_Annual</fullName>
            </value>
            <value>
                <fullName>EVS_Sales_Starter_2_Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Account_Profile__c</fullName>
    <label>Account Profile</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Solution Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Publisher_Status__c.field-meta.xml
<CustomField>
    <fullName>Publisher_Status__c</fullName>
    <description>Current status of the publisher&#39;s account.</description>
    <inlineHelpText>Current status of the publisher&#39;s account. Updated via sync from origin-services account.</inlineHelpText>
    <label>Publisher Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>UNREQUESTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>ENROLLED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>LOCKED</fullName>
            </value>
            <value>
                <fullName>LOCKED_NON_PAYMENT</fullName>
            </value>
            <value>
                <fullName>LOCKED_TRIAL_EXPIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BrightcoveAccountDataProcessorTest.cls
@isTest
public with sharing class BrightcoveAccountDataProcessorTest {
    @isTest
    static void testPost() {
        RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf(getRequestJson());
        RestContext.request = request;
        String responseJson = DataService.doPost();

        System.assertNotEquals(null, responseJson, 'Response was null.');

        Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(
            responseJson
        );

        System.assertEquals(
            true,
            (Boolean) response.get('success'),
            'Invocation was unsuccessful: ' + (String) response.get('message')
        );

        List<Brightcove_Account__c> brightAccounts = [
            SELECT Id, GUID__c
            FROM Brightcove_Account__c
            LIMIT 1
        ];
        System.assertEquals(
            1,
            brightAccounts.size(),
            'Incorrect number of records created.'
        );
    }

    static String getRequestJson() {
        Map<String, Object> requestMap = new Map<String, Object>{
            'requestName' => 'CreateBrightcoveAccounts',
            'data' => getDataMap()
        };

        return JSON.serialize(requestMap);
    }

    static Map<String, Object> getDataMap() {
        Map<String, SObjectField> fields = Brightcove_Account__c.getSObjectType()
            .getDescribe(SObjectDescribeOptions.DEFERRED)
            .fields.getMap();

        return new Map<String, Object>{
            'account_edition' => fields.get('Account_Edition__c')
                    .getDescribe()
                    .getPicklistValues()[0]
                .getValue(),
            'email_address' => 'BrightcoveAccountDataProcessorTest@example.com',
            'max_users' => 10,
            'account_profile' => fields.get('Account_Profile__c')
                    .getDescribe()
                    .getPicklistValues()[0]
                .getValue(),
            'publisher_status' => fields.get('Publisher_Status__c')
                    .getDescribe()
                    .getPicklistValues()[0]
                .getValue(),
            'tier' => fields.get('Tier__c').getDescribe().getPicklistValues()[0]
                .getValue(),
            'bc_account_id' => 'BrightcoveAccountDataProcess'
        };
    }
}