unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Brightcove Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Account_Profile__c</fullName>
    <label>Account Profile</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Solution Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DefaultDataServiceRetrieverTest.cls
@isTest
public with sharing class DefaultDataServiceRetrieverTest {
    @TestSetup
    static void makeData() {
        Brightcove_Account__c brightAccount = new Brightcove_Account__c(
            GUID__c = GuidUtility.generateGuid(),
            Brightcove_Account_Id__c = '12345',
            Account_Profile__c = Brightcove_Account__c.Account_Profile__c.getDescribe()
                    .getPicklistValues()[0]
                .getValue(),
            Email_Address__c = 'DefaultDataServiceRetrieverTest@example.com'
        );
        insert brightAccount;
    }

    @isTest
    private static void testGetBrightcoveAccount() {
        Brightcove_Account__c brightcoveAccount = [
            SELECT Id, GUID__c
            FROM Brightcove_Account__c
            LIMIT 1
        ];
        System.assertNotEquals(
            null,
            brightcoveAccount.GUID__c,
            'Test record does not have a GUID value.'
        );

        RestRequest req = new RestRequest();
        req.params.put('guid', brightcoveAccount.GUID__c);
        req.params.put('requestName', 'GetBrightcoveAccount');
        req.httpMethod = 'GET';

        RestContext.request = req;
        String responseJson = DataService.doGet();

        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(
            responseJson
        );

        System.assertEquals(
            true,
            (Boolean) responseMap.get('success'),
            'The response did not indicated success'
        );
    }

    @isTest
    private static void testGetEmptyResult() {
        RestRequest req = new RestRequest();
        req.params.put('guid', 'InvalidGuid');
        req.params.put('requestName', 'GetBrightcoveAccount');
        req.httpMethod = 'GET';

        RestContext.request = req;
        String responseJson = DataService.doGet();

        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(
            responseJson
        );

        System.assertEquals(
            false,
            (Boolean) responseMap.get('success'),
            'The response indicated success.'
        );

        System.assertEquals(
            'No record found for provided value.',
            (String) responseMap.get('message'),
            'Incorrect error message in response.'
        );
    }
}