unpackaged/main/default/objects/Opportunity/fields/Demo_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Stage_Set_Date__c</fullName>
    <label>Demo Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Discovery_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Discovery_Stage_Set_Date__c</fullName>
    <label>Discovery Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Meeting_Occurred_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Occurred_Stage_Set_Date__c</fullName>
    <label>Meeting Occurred Stage Set Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Meeting_Pending_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Pending_Stage_Set_Date__c</fullName>
    <label>Meeting Pending Stage Set Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Meeting_Scheduled_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Scheduled_Stage_Set_Date__c</fullName>
    <label>Meeting Scheduled Stage Set Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Negotiation_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Stage_Set_Date__c</fullName>
    <label>Negotiation Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Solution_Design_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Solution_Design_Stage_Set_Date__c</fullName>
    <label>Solution Design Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/OpportunityStageDateStamper.cls
public with sharing class OpportunityStageDateStamper extends FieldStamper {
    @TestVisible
    private static Map<String, SObjectField> stageFieldMap = new Map<String, SObjectField>{
        '1 - Discovery' => Opportunity.Discovery_Stage_Set_Date__c,
        '2 - Demo' => Opportunity.Demo_Stage_Set_Date__c,
        '3 - Solution Design & Evaluation' => Opportunity.Solution_Design_Stage_Set_Date__c,
        '4 - Negotiation' => Opportunity.Negotiation_Stage_Set_Date__c,
        '0 - Meeting Pending' => Opportunity.Meeting_Pending_Stage_Set_Date__c,
        '0 - Meeting Scheduled' => Opportunity.Meeting_Scheduled_Stage_Set_Date__c,
        '0 - Meeting Occurred' => Opportunity.Meeting_Occurred_Stage_Set_Date__c
    };

    public override void stamp(SObject sobj) {
        String stageName = (String) sobj.get(Opportunity.StageName);
        if (stageFieldMap.containsKey(stageName)) {
            SObjectField field = stageFieldMap.get(stageName);
            sobj.put(field, Date.today());
        }
    }
}