unpackaged/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/Partner_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner Relationship</label>
    <nameField>
        <displayFormat>Partner-{0000}</displayFormat>
        <label>Partner Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Relationships</relationshipLabel>
    <relationshipName>Partner_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Relationships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
                <isActive>false</isActive>
                <label>OEM</label>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
                <isActive>false</isActive>
                <label>Referral Partner</label>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <isActive>false</isActive>
                <label>Reseller</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityPartnerChangeHandler.cls
public with sharing class OpportunityPartnerChangeHandler {
    static List<Id> customerIds;
    static List<Id> partnerIds;
    static List<String> partnerTypes;
    static Map<String, Partner_Relationship__c> existingPartnerRelationships;
    static Map<String, Opportunity> existingOpps;

    public static void processEvents(
        List<Opportunity_Partner_Change__e> events
    ) {
        parseEventData(events);
        List<Partner_Relationship__c> deprecatedRelationships = new List<Partner_Relationship__c>();
        for (String key : existingPartnerRelationships.keySet()) {
            if (!existingOpps.containsKey(key)) {
                deprecatedRelationships.add(
                    existingPartnerRelationships.get(key)
                );
            }
        }

        delete deprecatedRelationships;
    }

    private static void parseEventData(
        List<Opportunity_Partner_Change__e> events
    ) {
        customerIds = new List<Id>();
        partnerIds = new List<Id>();
        partnerTypes = new List<String>();

        for (Opportunity_Partner_Change__e event : events) {
            customerIds.add(event.Customer_Id__c);
            partnerIds.add(event.Partner_Id__c);
            partnerTypes.add(event.Partner_Type__c);
        }

        setExistingPartnerRelationships();
        setExistingOpps();
    }

    private static void setExistingPartnerRelationships() {
        existingPartnerRelationships = new Map<String, Partner_Relationship__c>();
        List<Partner_Relationship__c> relationships = [
            SELECT Id, Customer_Account__c, Partner_Account__c, Type__c
            FROM Partner_Relationship__c
            WHERE
                Customer_Account__c IN :customerIds
                AND Partner_Account__c IN :partnerIds
                AND Type__c IN :partnerTypes
        ];

        for (Partner_Relationship__c relationship : relationships) {
            String key =
                String.valueOf(relationship.Customer_Account__c) +
                String.valueOf(relationship.Partner_Account__c) +
                relationship.Type__c;
            existingPartnerRelationships.put(key, relationship);
        }
    }

    private static void setExistingOpps() {
        existingOpps = new Map<String, Opportunity>();

        List<Opportunity> opps = [
            SELECT Id, AccountId, Partner__c, Partner_Type__c
            FROM Opportunity
            WHERE
                AccountId IN :customerIds
                AND Partner__c IN :partnerIds
                AND Partner_Type__c IN :partnerTypes
        ];

        for (Opportunity opp : opps) {
            String key =
                String.valueOf(opp.AccountId) +
                String.valueOf(opp.Partner__c) +
                opp.Partner_Type__c;
            existingOpps.put(key, opp);
        }
    }
}