unpackaged/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/Partner_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner Relationship</label>
    <nameField>
        <displayFormat>Partner-{0000}</displayFormat>
        <label>Partner Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Relationships</relationshipLabel>
    <relationshipName>Partner_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Relationships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
                <isActive>false</isActive>
                <label>OEM</label>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
                <isActive>false</isActive>
                <label>Referral Partner</label>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <isActive>false</isActive>
                <label>Reseller</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OppPartnerRelationshipHandler.cls
/**
 * Most of this class' functionality is validated in OpportunityPartnerChangeHandlerTest,
 * with the exception of the publishing of the Opportunity_Partner_Change__e events, which
 * is validated as part of OpportunityPartnerChangeHandlerTest/
 */
public with sharing class OppPartnerRelationshipHandler extends DomainLogicHandler {
    List<Id> customerIds = new List<Id>();
    List<Id> partnerIds = new List<Id>();
    List<String> partnerTypes = new List<String>();
    Map<String, Opportunity> qualifiedOppsMap = new Map<String, Opportunity>();
    List<Opportunity_Partner_Change__e> oppPartnerChangeEvents = new List<Opportunity_Partner_Change__e>();

    public override void check(Sobject newObj) {
        Opportunity newOpp = (Opportunity) newObj;
        if (isQualified(newOpp)) {
            addQualifiedData(newOpp);
        }
    }

    public override void check(Sobject newObj, sobject oldObj) {
        Opportunity newOpp = (Opportunity) newObj;
        Opportunity oldOpp = (Opportunity) oldObj;
        if (isQualified(newOpp, oldOpp)) {
            addQualifiedData(newOpp);
        }
    }

    public override void processRecords() {
        filterExistingRelationships();
        createPartnerRelationshipRecords();
        if (!oppPartnerChangeEvents.isEmpty()) {
            Eventbus.publish(oppPartnerChangeEvents);
        }
    }

    private void addQualifiedData(Opportunity newOpp) {
        customerIds.add(newOpp.AccountId);
        partnerIds.add(newOpp.Partner__c);
        partnerTypes.add(newOpp.Partner_Type__c);

        String key =
            String.valueOf(newOpp.AccountId) +
            newOpp.Partner__c +
            newOpp.Partner_Type__c;
        qualifiedOppsMap.put(key, newOpp);
    }

    private Boolean isQualified(Opportunity newOpp) {
        return newOpp.Partner__c != null;
    }

    private Boolean isQualified(Opportunity newOpp, Opportunity oldOpp) {
        return isChanged(newOpp, oldOpp) && isQualified(newOpp);
    }

    private Boolean isChanged(Opportunity newOpp, Opportunity oldOpp) {
        if (
            newOpp.Partner__c != oldOpp.Partner__c ||
            newOpp.Partner_Type__c != oldOpp.Partner_Type__c
        ) {
            oppPartnerChangeEvents.add(
                new Opportunity_Partner_Change__e(
                    Opportunity_Id__c = oldOpp.Id,
                    Customer_Id__c = oldOpp.AccountId,
                    Partner_Id__c = oldOpp.Partner__c,
                    Partner_Type__c = oldOpp.Partner_Type__c
                )
            );
            return true;
        }
        return false;
    }

    private void filterExistingRelationships() {
        List<Partner_Relationship__c> partnerRelationships = [
            SELECT Id, Partner_Account__c, Customer_Account__c, Type__c
            FROM Partner_Relationship__c
            WHERE
                Partner_Account__c IN :partnerIds
                AND Customer_Account__c IN :customerIds
                AND Type__c IN :partnerTypes
        ];

        for (
            Partner_Relationship__c partnerRelationship : partnerRelationships
        ) {
            String key =
                String.valueOf(partnerRelationship.Customer_Account__c) +
                partnerRelationship.Partner_Account__c +
                partnerRelationship.Type__c;
            qualifiedOppsMap.remove(key);
        }
    }

    private void createPartnerRelationshipRecords() {
        List<Partner_Relationship__c> partnerRelationships = new List<Partner_Relationship__c>();
        for (Opportunity opps : qualifiedOppsMap.values()) {
            Partner_Relationship__c partnerRecord = new Partner_Relationship__c(
                Partner_Account__c = opps.Partner__c,
                Customer_Account__c = opps.AccountId,
                Type__c = opps.Partner_Type__c,
                Active__c = true
            );
            partnerRelationships.add(partnerRecord);
        }

        insert partnerRelationships;
    }
}