unpackaged/main/default/objects/Opportunity/fields/Qualifier_Role__c.field-meta.xml
<CustomField>
    <fullName>Qualifier_Role__c</fullName>
    <label>Qualifier Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDR</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Qualifying_User__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Qualifying User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Qualified_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/OpportunityQualificationHandler.cls
public with sharing class OpportunityQualificationHandler extends DomainLogicHandler {
    private List<Opportunity> qualifiedOpps = new List<Opportunity>();
    private Id bdrRoleId;

    public override void check(Sobject newObj, SObject oldObj) {
        Opportunity newOpp = (Opportunity) newObj;
        if (isQualified(newOpp, oldObj)) {
            qualifiedOpps.add(newOpp);
        }
    }

    public override void processRecords() {
        if (!qualifiedOpps.isEmpty()) {
            setBrdRoleId();
            for (Opportunity newOpp : qualifiedOpps) {
                setQualiferFields(newOpp);
            }
        }
    }

    private Boolean isQualified(Opportunity newOpp, SObject oldOpp) {
        return TriggerUtility.isChanged(
                newOpp,
                oldOpp,
                Opportunity.StageName
            ) && newOpp.StageName == '0 - Meeting Occurred';
    }

    private void setBrdRoleId() {
        bdrRoleId = [SELECT Id FROM UserRole WHERE Name = 'BDR'].Id;
    }

    private void setQualiferFields(Opportunity newOpp) {
        newOpp.Qualifying_User__c = UserInfo.getUserId();
        newOpp.Qualifier_Role__c = UserInfo.getUserRoleId() == bdrRoleId
            ? 'BDR'
            : 'Sales Rep';
    }
}