unpackaged/main/default/objects/Domain_Handler__mdt/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <label>SObject Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Log__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>OpportunityLineItem</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Domain_Handler__mdt/fields/Trigger_Event__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Event__c</fullName>
    <label>Trigger Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE_INSERT</fullName>
                <default>true</default>
                <label>BEFORE_INSERT</label>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DomainHandlerUtility.cls
public with sharing class DomainHandlerUtility {
    List<DomainLogicHandler> handlers;
    String triggerEvent = Trigger.operationType.name();

    public DomainHandlerUtility() {
        setDomainHandlers();
    }

    public void process() {
        String dml = triggerEvent.split('_')[1];
        switch on dml {
            when 'INSERT' {
                processInsert();
            }
            when 'UPDATE' {
                processUpdate();
            }
        }

        processHandlers();
    }

    void processInsert() {
        for (SObject newObj : Trigger.new) {
            for (DomainLogicHandler handler : handlers) {
                handler.check(newObj);
            }
        }
    }

    void processUpdate() {
        for (SObject newObj : Trigger.new) {
            SObject oldObj = Trigger.oldMap.get(newObj.Id);
            for (DomainLogicHandler handler : handlers) {
                handler.check(newObj, oldObj);
            }
        }
    }

    void processHandlers() {
        for (DomainLogicHandler handler : handlers) {
            handler.processRecords();
        }
    }

    void setDomainHandlers() {
        String sobjectName = getSObjectName();
        List<Domain_Handler__mdt> domainHandlers = [
            SELECT Label, Handler_Class__c, Trigger_Event__c
            FROM Domain_Handler__mdt
            WHERE
                SObject_Name__c = :sobjectName
                AND Trigger_Event__c = :triggerEvent
                AND Active__c = TRUE
        ];

        handlers = new List<DomainLogicHandler>();
        for (Domain_Handler__mdt domainHandler : domainHandlers) {
            Type myType = Type.forName(domainHandler.Handler_Class__c);
            if (myType != null) {
                DomainLogicHandler handler = (DomainLogicHandler) myType.newInstance();
                handlers.add(handler);
            }
        }
    }

    String getSObjectName() {
        SObject sobj = Trigger.new == null ? Trigger.old[0] : Trigger.new[0];
        return sobj.getSobjectType().getDescribe().getName();
    }
}